Clientmanagement
TheWannaBs/Mean_Stack pull request #4
Opened 2017-10-09 23:03 UTC by wcampbell09

2017-10-09 23:24 UTC, angryoctopode commented on modules/clientmanagements/client/config/clientmanagements.client.routes.js
> +          roles: ['user', 'admin'],
You can just throw this under the abstract state, 'clientmanagements'

2017-10-09 23:24 UTC, angryoctopode commented on modules/clientmanagements/client/config/clientmanagements.client.routes.js
> +          roles: ['user', 'admin'],
You can just throw this under the abstract state, 'clientmanagements'

2017-10-09 23:26 UTC, angryoctopode commented on modules/clientmanagements/client/config/clientmanagements.client.routes.js
> +      })
add data: {
  roles: [/* Insert roles here */]
}

2017-10-09 23:26 UTC, dkwhite200 commented on modules/clientmanagements/client/views/list-clientmanagements.client.view.html
> +                  <tr ng-repeat="clientmanagement in vm.clientmanagements | filter: query" ui-sref= "clientmanagements.view({clientmanagementId:
Fix this indentation

2017-10-09 23:26 UTC, angryoctopode commented on modules/clientmanagements/client/config/clientmanagements.client.routes.js
> +        template: '<ui-view/>'
add data: {
roles: [/* Insert roles here */]
}

2017-10-09 23:29 UTC, eristow approved these changes
All is good.

2017-10-09 23:31 UTC, AriTheGuitarMan commented on modules/clientmanagements/client/config/clientmanagements.client.routes.js
> +        template: '<ui-view/>'
Logical

2017-10-09 23:31 UTC, dkwhite200 approved these changes
Go for it

2017-10-09 23:31 UTC, wcampbell09 reviewed
Good stuff

2017-10-09 23:32 UTC, angryoctopode requested changes
Please fix these app breaking things, ASAP.

2017-10-10 00:18 UTC, angryoctopode commented on modules/clientmanagements/client/config/clientmanagements.client.routes.js
> +        template: '<ui-view/>'
Looks gucci now. 👍

2017-10-10 00:19 UTC, angryoctopode commented on modules/clientmanagements/client/config/clientmanagements.client.routes.js
> +        template: '<ui-view/>'
0/10. Missing comma after line. 👎

2017-10-10 00:19 UTC, dkwhite200 commented on modules/clientmanagements/client/config/clientmanagements.client.routes.js
> +        template: '<ui-view/>'
MY EYES

2017-10-10 00:28 UTC, dkwhite200 approved these changes
Nice Job

2017-10-10 00:28 UTC, angryoctopode approved these changes

2017-10-10 00:28 UTC, AriTheGuitarMan approved these changes
The table looks nice. Good. Make sure routes work well.

2017-10-10 00:36 UTC, merged